/*
 * Copyright (C) 2022 Lingu Light Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package space.lingu.light;

import java.lang.annotation.*;

/**
 * Index
 *
 * @author RollW
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(value = {})
public @interface Index {
    /**
     * Columns included in the index.
     *
     * @return Columns included in the index
     */
    String[] value();

    /**
     * Order
     *
     * @return Orders
     * @see Order#ASC
     * @see Order#DESC
     */
    Order[] orders() default {};

    /**
     * Index name.
     * <p>
     * Leave it empty to let generated by Light.
     *
     * @return index name
     */
    String name() default "";

    /**
     * If is unique index or not.
     *
     * @return is unique
     */
    boolean unique() default false;


    LightConfiguration[] configurations() default {};
}
